### ISSUE TITLE
Pictos not shown.

### ISSUE THREAD

**Issue by philippeowagner** [rs/gls#2]
Does not work for me, installed using brew. `gls` works

**Comment by rs** [comment]
You mean no icons are shown? Can you send a screenshot? Witch version of iTerm do you have?

**Comment by philippeowagner** [comment]
iTerm: Build 2.1.1
OS X: 10.10.5

![screen shot 2015-09-07 at 13 54 22](https://cloud.githubusercontent.com/assets/113043/9716267/6f0986de-5568-11e5-9899-71bb6b0b3ef1.png)

Same for other directories, this shows "/tmp"

**Comment by Sniperovitch** [comment]
No icons are shown here with 2.1.1. It's ok with 2.9.20150830 (beta)

**Comment by rs** [comment]
Yes it does only work with beta. I added version requirement to the readme.

**Comment by philippeowagner** [comment]
Cool! Works! Thanks
